version: 2.0

workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          brew install cocoapods || echo "CocoaPods is already installed"
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          fi
          pod install
      - name: Build iOS
        script: |
          flutter clean
          flutter pub get
          flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
